export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR"

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR"

export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR"