export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS"
export const CREATE_RECORD_ERROR = "CREATE_RECORD_ERROR"

export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS"
export const DELETE_RECORD_ERROR = "DELETE_PROJECT_ERROR"